version: '3.8'

services:
  mock-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: mock-api:latest
    container_name: mock-api-service
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
      - PORT=4001
      - LOG_LEVEL=info
    restart: unless-stopped
    networks:
      - mock-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mock-network:
    driver: bridge